backend:
  name: netlify-api
  url: http://localhost:8080
production:
  backend:
    name: github-api
    repo: dorelljames/business-static-new-template
    branch: master
media_folder: assets/img/uploads
public_folder: assets
collections:
  - name: sitedata
    label: Site Information
    create: false
    files:
      - name: sitedata
        label: Site Information
        file: data/site.json
        description: edit site setting
        fields:
          - label: Site Information
            name: sitedata
            widget: list
            fields:
              - label: Favicon
                name: icon
                widget: image
                media_folder: assets/img
              - label: Site Logo
                name: logo
                widget: image
                media_folder: assets/img
              - label: Site name
                name: sitename
                widget: string
              - label: Website Description
                name: metadesc
                widget: string
              - label: Author
                name: metauthor
                widget: string
              - label: Keywords
                name: metakeyword
                widget: string
              - label: Footer
                name: footer
                widget: markdown
              - label: Google Analytics
                name: analytics
                widget: markdown
  - name: slide
    label: Image Slider
    files:
      - name: slider
        label: Image Slide
        file: data/slider.json
        description: image slider
        fields:
          - label: Default Slider Text
            name: slidetxt
            widget: list
            fields:
              - label: Image
                name: sliderlogo
                widget: image
                media_folder: assets/img
              - label: Slider Text
                name: slidertxt
                widget: string
              - label: Slider Description
                name: sliderdesc
                widget: string
          - label: Image Slider
            name: slide
            widget: list
            fields:
              - label: Image
                name: image
                widget: image
                media_folder: assets/img
              - label: Name
                name: name
                widget: string
  - name: services2
    label: Local Columns
    files:
      - name: localcolumns
        label: Local Columns
        file: data/localcolumns.json
        description: Add local columns entries here
        fields:
          - label: Local Columns
            name: localcolumns
            widget: list
            fields:
              - label: Title
                name: title2
                widget: string
              - label: Publish Date
                name: date2
                widget: datetime
              - label: Main Image
                name: mainimage2
                widget: image
                media_folder: assets/localcolumns
              - label: Thumbnail
                name: thumbnail2
                widget: image
                media_folder: assets/localcolumns
              - label: Category
                name: category2
                widget: string
              - label: Shortdesc
                name: shortdesc2
                widget: string
              - label: Post Body
                name: postbody2
                widget: markdown
  - name: services
    label: Services
    folder: services
    create: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Banner
        name: banner
        widget: image
        class: image featured
      - label: Short Description
        name: shortdesc
        widget: string
      - label: Body
        name: body
        widget: markdown
    meta:
      - label: Publish Date
        name: date
        widget: datetime
      - label: Categories
        name: categories
        widget: string
  - name: work
    label: Featured Work
    folder: featuredwork
    create: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Banner
        name: banner
        widget: image
        class: image featured
        media_folder: assets/img
      - label: Short Description
        name: shortdesc
        widget: string
      - label: Body
        name: body
        widget: markdown
    meta:
      - label: Publish Date
        name: date
        widget: datetime
      - label: Categories
        name: categories
        widget: string
  - name: news
    label: News
    folder: news
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Banner
        name: banner
        widget: image
        class: image featured
        media_folder: assets/img
      - label: Short Description
        name: shortdesc
        widget: string
      - label: Body
        name: body
        widget: markdown
    meta:
      - label: Publish Date
        name: date
        widget: datetime
      - label: Categories
        name: categories
        widget: string
  - name: testi
    label: Testimonial
    files:
      - name: client
        label: Testimonial
        file: data/client.json
        description: client testimonial
        fields:
          - label: Testimonial
            name: testi
            widget: list
            fields:
              - label: Avatar
                name: image
                widget: image
                media_folder: assets/img
              - label: Name
                name: name
                widget: string
              - label: Work
                name: work
                widget: string
              - label: Comment
                name: comment
                widget: string
  - name: data
    label: Partners Logo
    files:
      - name: partners
        label: Our Partners
        file: data/partners.json
        description: partners logo
        fields:
          - label: Our Partners
            name: data
            widget: list
            fields:
              - label: Logo
                name: logo
                widget: image
                media_folder: assets/img/partners
              - label: Website
                name: website
                widget: string
  - name: filemanager
    label: File Manager
    files:
      - name: filemanager
        label: File Manager
        file: data/files.json
        description: Add file(image,doc,pdf) here
        fields:
          - label: File Manager
            name: filemanager
            widget: list
            fields:
              - label: File Name
                name: name
                widget: string
              - label: File Type
                name: file
                widget: image
                media_folder: assets/files
